export const addCars = [
  {
    id: 1,
    image: "/image/carBg6.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 2,
    image: "/image/carBg1.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 3,
    image: "/image/car12.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 4,
    image: "/image/carBg3.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 5,
    image: "/image/car8.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 6,
    image: "/image/car5.jfif",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },
];