export const addCars = [
  {
    id: 1,
    image: "/image2/car.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 2,
     image: "/image2/car1.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 3,
    image: "/image2/car2.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 4,
    image: "/image2/car3.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 5,
 image: "/image2/car4.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    transmission: "Manual",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },

   {
    id: 6,
   image: "/image2/car5.jpg",
    useBy: "Nigeria Used",
    year: "2024",
    model: "KIA Sorento",
    body: "SUV",
    fuel: "Diesel",
    price: 35000000,
    map: "/map.jfif",
    location: "Lagos",
  },
];