// lib/pendingApproval.js

export const alluser = [
  {
    id: 1,
    icon: FaListOl,
    dealer: "Chukwuemaka K.",
    email: "chukwuemaka@gmail.com",
    phone: "+234 7039325432",
    location: "Ojota",
    joined: "jan 2026",
    enquiries: 2,
    status: "Verified",
    action: "Subpend",
    view: "View",
  },
  {
    id: 2,
    icon: GiSellCard,
    dealer: "Amina Yusuf",
    email: "aminayusuf@gmail.com",
    phone: "+234 804536657",
    location: "Lekki",
    joined: "Mar 2025",
    enquiries: 1,
    status: "pending",
    action: "Subpend",
    view: "View",
  },

  {
    id: 3,
    icon: RiPassPendingFill,
    dealer: "Ngalaka Gift",
    email: "ngalakagift@gmail.com",
    phone: "+234 7039307654",
    location: "Rivers",
    joined: "july 2026",
    enquiries: 2,
    status: "Unverified",
    action: "Subpend",
    view: "Verify",
  },
  {
    id: 3,
    icon: IoShieldOutline,
    dealer: "Ngalaka Gift",
    email: "ngalakagift@gmail.com",
    phone: "+234 7039307654",
    location: "Rivers",
    joined: "july 2026",
    enquiries: 2,
    status: "Unverified",
    action: "Subpend",
    view: "Verify",
  },
];
